apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.app.name }}-app
  labels:
    {{- include "currency-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "currency-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "currency-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
